spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: 123456
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=NhaTroASM
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: uehsokvuasrjtert
    port: 587
    properties:
      mail:
        smpt:
          auth: true
        smtp:
          starttls:
            enable: true
    username: 0tringuyen46@gmail.com

  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:src/main/resources/static/
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 
            client-secret: 
            scope:
              - email
              - public_profile
          google:
            client-id:
            client-secret: 
  thymeleaf:
     prefix: classpath:/templates/
     suffix: .html
  servlet:
     multipart:
       max-file-size: 50MB
       max-request-size: 50MB

     
      